# https://eksctl.io/usage/schema/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: chaos-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    minSize: 2
    maxSize: 3
    ssh:
      allow: true
